### ISSUE TITLE
Certain characters crash the program in encoding

### ISSUE THREAD

**Issue by shawnmcla** [shawnmcla/shudder#1]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Dev\Python\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Dev\Python\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Dev\node\Bots\cambot\lib\irc.py", line 76, in _receiveLoop
    print(response)
  File "D:\Dev\Python\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 64-69: character maps to <undefined>
```

Easy fix, just a reminder

**Comment by shawnmcla** [comment]
Fixed with #2
